/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.principal.vistas;


import gui.personas.vistas.VentanaNuevoAlumno;
import gui.personas.vistas.VentanaNuevoProfesor;
import gui.areas.vistas.VentanaNuevaArea;
import gui.trabajos.vistas.VentanaNuevoTrabajo;



/**
 *
 * @author prog2
 */
public class VentanaNuevoPrincipal extends javax.swing.JFrame {
    /* Declarar variables, 
    por ejemplo la lista en la que se agregarán los objetos*/
    
    /**
     * Constructor de VentanaNuevo
     */
    public VentanaNuevoPrincipal() {
        initComponents();
        this.setVisible(true);  
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAreas = new javax.swing.JButton();
        btnAlumnos = new javax.swing.JButton();
        btnDocentes = new javax.swing.JButton();
        btnTrabajos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recursos - Nuevo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAreas.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        btnAreas.setText("Areas");
        btnAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAreas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 341, 44));

        btnAlumnos.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        btnAlumnos.setText("Alumnos");
        btnAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 341, 41));

        btnDocentes.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        btnDocentes.setText("Docentes");
        btnDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocentesActionPerformed(evt);
            }
        });
        getContentPane().add(btnDocentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 341, 41));

        btnTrabajos.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        btnTrabajos.setText("Trabajos");
        btnTrabajos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrabajosActionPerformed(evt);
            }
        });
        getContentPane().add(btnTrabajos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 341, 39));

        jLabel1.setFont(new java.awt.Font("Ubuntu Mono", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(225, 17, 1));
        jLabel1.setText("Super Programa 3.0");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 440, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thanos.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreasActionPerformed

       VentanaNuevaArea VentanaNuevaArea = new VentanaNuevaArea (null);
    }//GEN-LAST:event_btnAreasActionPerformed

    private void btnAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosActionPerformed

        VentanaNuevoAlumno VentanaNuevoAlumno = new VentanaNuevoAlumno (null);
    }//GEN-LAST:event_btnAlumnosActionPerformed

    private void btnDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocentesActionPerformed

        VentanaNuevoProfesor VentanaNuevoProfesor = new VentanaNuevoProfesor (null);
    }//GEN-LAST:event_btnDocentesActionPerformed

    private void btnTrabajosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrabajosActionPerformed
        
        VentanaNuevoTrabajo VentanaNuevoTrabajo = new VentanaNuevoTrabajo (null); 
    }//GEN-LAST:event_btnTrabajosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumnos;
    private javax.swing.JButton btnAreas;
    private javax.swing.JButton btnDocentes;
    private javax.swing.JButton btnTrabajos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
